# Generated by Django 5.2.1 on 2025-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cidade_natal', models.CharField(max_length=100)),
                ('estado_natal', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_residencia', models.CharField(max_length=100)),
                ('estado_residencia', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('contato_emergencia', models.CharField(max_length=255)),
                ('tipo_sanguineo', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
