# Generated by Django 5.2.1 on 2025-05-20 19:56

import django.core.validators
import sndot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sndot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[sndot.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='doador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doador',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='A idade deve ser maior ou igual a 0.'), django.core.validators.MaxValueValidator(125, message='A idade deve ser menor ou igual a 125.')]),
        ),
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O-'), ('O-', 'O-')], max_length=5),
        ),
    ]
