# Generated by Django 5.2.1 on 2025-05-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sndot', '0002_alter_doador_cpf_alter_doador_id_alter_doador_idade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.AlterField(
            model_name='doador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viuvo'), ('Uniao Estavel', 'Uniao Estavel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='estado_natal',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='doador',
            name='estado_residencia',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.CreateModel(
            name='IntencaoDeDoar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intencao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='ativa', max_length=50)),
                ('doar_agora', models.BooleanField(default=False)),
                ('doador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intencao_doar', to='sndot.doador')),
                ('orgaos', models.ManyToManyField(blank=True, to='sndot.orgao')),
            ],
            options={
                'verbose_name': 'Intenção de Doar',
                'verbose_name_plural': 'Intenções de Doar',
            },
        ),
    ]
